extern int bound(int x, int b);
extern void boundVec(int32_t *values, int32_t bound, int32_t len);
extern int type(ent *e);
extern void getSize(int32_t *dest, ent *e);
extern char getTrigger(ent *e, int i);
extern char getButton(ent *e, int i);
extern void getAxis(int32_t *dest, ent *e);
extern void getLook(int32_t *dest, ent *e);
extern void getPos(int *dest, ent *a, ent *b);
extern void getVel(int *dest, ent *a, ent *b);
extern int getSlider(ent *e, int ix);
