extern void pushBtn(ent *who, int ix);
extern void uCenter(ent *e, int32_t *p);
extern void uVel(ent *e, int32_t *a);
extern void uDead(gamestate *gs, ent *e);
extern void uDrop(gamestate *gs, ent *e);
extern void uErase(gamestate *gs, ent *e);
extern void uPickup(gamestate *gs, ent *e, ent *p, int32_t holdFlags);
extern void uSlider(ent *e, int ix, int32_t value);
extern void uWire(ent *e, ent *w);
extern void uUnwire(ent *e, ent *w);
extern void uMyTypeMask(ent *e, uint32_t mask);
extern void uMyCollideMask(ent *e, uint32_t mask);
extern void updateTrajectory(ent *who, int32_t *old, int32_t *center, int32_t *vel);
