extern void pushBtn(ent *who, int ix);
extern void pushAxis1(ent *who, int *x);
extern void pushEyes(ent *who, int *x);
extern void uCenter(ent *e, int32_t *p);
extern void uVel(ent *e, int32_t *a);
extern void uDead(gamestate *gs, ent *e);
extern void uDrop(gamestate *gs, ent *e);
extern void uPickup(gamestate *gs, ent *e, ent *p);
extern void uStateSlider(ent *e, int ix, int32_t value);
extern void uWire(ent *e, ent *w);
extern void uUnwire(ent *e, ent *w);
extern void uMyTypeMask(ent *e, uint32_t mask);
extern void uMyCollideMask(ent *e, uint32_t mask);
